# SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, TOTAL_SALES
# FROM BOOK A, AUTHOR B, BOOK_SALES C
# WHERE (B.AUTHOR_NAME ,A.CATEGORY) IN (
#     SELECT B.AUTHOR_NAME,A.CATEGORY 
#     FROM BOOK A, AUTHOR B, BOOK_SALES C
#     WHERE C.BOOK_ID = A.BOOK_ID
#     AND B.AUTHOR_ID = A.AUTHOR_ID
#     AND SUBSTR(C.SALES_DATE, 1, 7) <= "2022-01"
#     GROUP BY B.AUTHOR_NAME, A.CATEGORY
# )
# AND C.BOOK_ID = A.BOOK_ID
# AND B.AUTHOR_ID = A.AUTHOR_ID

SELECT  A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE*C.SALES) AS TOTAL_SALES
FROM BOOK A, AUTHOR B, BOOK_SALES C
WHERE C.BOOK_ID = A.BOOK_ID
AND B.AUTHOR_ID = A.AUTHOR_ID
AND SUBSTR(C.SALES_DATE, 1, 7) <= "2022-01"
GROUP BY B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC
;