-- 코드를 작성해주세요
SELECT A.ID, COALESCE(B.CHILD_COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN 
    (SELECT A.ID, COUNT(*) CHILD_COUNT
    FROM ECOLI_DATA A
    JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID
    GROUP BY A.ID) 
AS B
ON A.ID = B.ID
ORDER BY A.ID
;