-- 코드를 입력하세요
# SELECT * FROM PRODUCT;
# SELECT * FROM OFFLINE_SALE;

SELECT A.PRODUCT_CODE, A.PRICE*SUM(B.SALES_AMOUNT) SALES
FROM PRODUCT A, OFFLINE_SALE B
WHERE A.PRODUCT_ID=B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY (A.PRICE*SUM(B.SALES_AMOUNT)) DESC, A.PRODUCT_CODE ASC
;