# -- 코드를 입력하세요
SELECT substr(SALES_DATE,1,10) SALES_DATE ,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM (
    (
        SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
        FROM ONLINE_SALE
        WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
    )
    UNION ALL
    (
        SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
        FROM OFFLINE_SALE 
        WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
    )
) AS T

ORDER BY SALES_DATE ,PRODUCT_ID, USER_ID;

 # SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
 #    FROM OFFLINE_SALE 
 #    WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3;
 
 # SELECT * FROM OFFLINE_SALE ;