-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME ,CONCAT(B.CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) 전체주소, 
CONCAT(SUBSTR(TLNO,1,3),"-", SUBSTR(TLNO,4,4),"-",SUBSTR(TLNO,8,4)) 전화번호
FROM USED_GOODS_BOARD A, USED_GOODS_USER B 
WHERE A.WRITER_ID = B.USER_ID 
GROUP BY B.USER_ID
HAVING COUNT(B.NICKNAME)>=3
ORDER BY B.USER_ID DESC
;