-- 코드를 입력하세요
SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,
 case 
    WHEN FREEZER_YN is NULL then 'N'
    else FREEZER_YN END
    as FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE SUBSTR(ADDRESS, 1,3)='경기도'
order by WAREHOUSE_ID;