SELECT CAR_ID, ROUND(AVG((DATEDIFF(END_DATE,START_DATE)+1)),1) AVERAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) >=6
ORDER BY ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) DESC, CAR_ID DESC;
