-- 코드를 입력하세요


SELECT A.FLAVOR
FROM (
    SELECT FLAVOR , SUM(TOTAL_ORDER) SUM
    FROM FIRST_HALF
    GROUP BY FLAVOR
) A, (SELECT FLAVOR , SUM(TOTAL_ORDER) SUM
FROM JULY
GROUP BY FLAVOR) B
WHERE A.FLAVOR = B.FLAVOR
ORDER BY (A.SUM+ B.SUM) DESC
LIMIT 3
;