-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, C.MCDP_CD,B.DR_NAME,C.APNT_YMD
FROM PATIENT A, DOCTOR B, APPOINTMENT C
WHERE C.PT_NO = A.PT_NO 
AND C.MDDR_ID = B.DR_ID
AND C.APNT_CNCL_YN ='N'
AND SUBSTR(C.APNT_YMD,1,10) = "2022-04-13"
AND C.MCDP_CD = "CS"
ORDER BY C.APNT_YMD
;