-- 코드를 입력하세요
SET @HOUR_VAR = -1;
SELECT @HOUR_VAR:= @HOUR_VAR +1  HOUR 
    ,(SELECT COUNT (*)
      FROM ANIMAL_OUTS 
      WHERE HOUR(DATETIME) = @HOUR_VAR)
      COUNT
 FROM ANIMAL_OUTS
 WHERE @HOUR_VAR < 23
;

