-- 코드를 입력하세요
# SELECT * FROM MEMBER_PROFILE ;

SELECT MEMBER_ID, MEMBER_NAME,GENDER, SUBSTR(DATE_OF_BIRTH,1,10) DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE MONTH(DATE_OF_BIRTH) = 3 
AND TLNO IS NOT NULL
AND GENDER = 'W'
ORDER BY MEMBER_ID
;