SELECT CONCAT("/home/grep/src/",A.BOARD_ID, "/",FILE_ID,FILE_NAME,FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD  A, USED_GOODS_FILE B
WHERE A.BOARD_ID = B.BOARD_ID
AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY  FILE_ID DESC
;

# SELECT * FROM USED_GOODS_BOARD
# ORDER BY VIEWS DESC;