-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) TOTAL_SALES
FROM BOOK A, BOOK_SALES B
WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
AND A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY
;