# SELECT *
# FROM BOOK ;

# SELECT *
# FROM AUTHOR;

SELECT A.BOOK_ID,B.AUTHOR_NAME,SUBSTR(A.PUBLISHED_DATE,1,10) PUBLISHED_DATE
FROM BOOK A, AUTHOR B
WHERE A.AUTHOR_ID = B.AUTHOR_ID 
AND A.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
;